name: 'Jira label issues from Release notes.'
description: 'A little github action to label issues getting the issues from the release text'
inputs:
  version:
    description: 'From which version should we get the release text?'
    required: true
    default: ''
  github-access-token:
    description: 'The GitHub access token required to delete the assets & discover non released versions'
    required: true
    default: ''
  tag:
    description: 'The tag to assign to the issues'
    required: false
    default: 'PRE-PROD'
  jira-url:
    description: 'The Jira URL'
    required: true
    default: ''
  jira-user:
    description: 'The Jira username for the basic auth'
    required: true
    default: ''
  jira-password:
    description: 'The Jira basic auth password'
    required: true
    default: ''
  project-prefix:
    description: 'The Jira project prefix'
    required: true
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
  
branding:
  icon: 'bookmark'  
  color: 'gray-dark'
