name: 'Jira label issues from Release notes.'
description: 'A little github action to label issues getting the issues from the release text'
inputs:
  github-access-token:
    description: 'The GitHub access token required to delete the assets & discover non released versions'
    required: true
    default: ''
  environment:
    description: 'The environment to use for the action'
    required: false
    default: 'PRE-PROD'
runs:
  using: 'node16'
  main: 'dist/index.js'
  
branding:
  icon: 'bookmark'  
  color: 'gray-dark'
